name: Scanner
on:
  schedule:
    - cron: '0 */3 * * *'  # Every 3 hours
  workflow_dispatch:  # Manual trigger

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python3 bot.py  # Manual mode
          python3 -c "from bot import automated_scan; automated_scan()"  # Auto-scan
